package com.zeroheat.lolandroll.datas

import java.io.Serializable

class matchPartyPeople(

var  assists	:Int,
var  baronKills	:Int,
var  bountyLevel:Int,
var  champExperience:Int,
var  champLevel	:Int,
var  championId	:Int,
var  championName	:String,
var  championTransform	:Int,
var  consumablesPurchased:Int,
var  damageDealtToBuildings:Int,
var  damageDealtToObjectives:Int,
var  damageDealtToTurrets:Int,
var  damageSelfMitigated:Int,
var  deaths	:Int,
var  detectorWardsPlaced:Int,
var  doubleKills:Int,
var  dragonKills:Int,
var  firstBloodAssist:Boolean,
var  firstBloodKill	:Boolean,
var  firstTowerAssist:Boolean,
var  firstTowerKill	:Boolean,
var  gameEndedInEarlySurrender:Boolean,
var  gameEndedInSurrender	:Boolean,
var  goldEarned:Int,
var  goldSpent	:Int,
var  individualPosition:String,
var  inhibitorKills	:Int,
var  inhibitorTakedowns	:Int,
var  inhibitorsLost	:Int,
var  item0	:Int,
var  item1	:Int,
var  item2	:Int,
var  item3	:Int,
var  item4	:Int,
var  item5	:Int,
var  item6	:Int,
var  itemsPurchased	:Int,
var  killingSprees	:Int,
var  kills	:Int,
var  lane	:String,
var  largestCriticalStrike	:Int,
var  largestKillingSpree	:Int,
var  largestMultiKill	:Int,
var  longestTimeSpentLiving	:Int,
var  magicDamageDealt	:Int,
var  magicDamageDealtToChampions:Int,
var  magicDamageTaken:Int,
var  neutralMinionsKilled:Int,
var  nexusKills:Int,
var  nexusTakedowns	:Int,
var  nexusLost	:Int,
var  objectivesStolen:Int,
var  objectivesStolenAssists:Int,
var  participantId:Int,
var  pentaKills	:Int,
var  physicalDamageDealt:Int,
var  physicalDamageDealtToChampions:Int,
var  physicalDamageTaken:Int,
var  profileIcon:Int,
var  puuid	:String,
var  quadraKills:Int,
var  riotIdName	:String,
var  riotIdTagline	:String,
var  role	:String,
var  sightWardsBoughtInGame:Int,
var  spell1Casts	:Int,
var  spell2Casts	:Int,
var  spell3Casts	:Int,
var  spell4Casts	:Int,
var  summoner1Casts	:Int,
var  summoner1Id	:Int,
var  summoner2Casts	:Int,
var  summoner2Id	:Int,
var  summonerId	:String,
var  summonerLevel	:Int,
var  summonerName	:String,
var  teamEarlySurrendered:Boolean,
var  teamId	:Int,
var  teamPosition	:String,
var  timeCCingOthers	:Int,
var  timePlayed	:Int,
var  totalDamageDealt	:Int,
var  totalDamageDealtToChampions	:Int,
var  totalDamageShieldedOnTeammates	:Int,
var  totalDamageTaken	:Int,
var  totalHeal	:Int,
var  totalHealsOnTeammates:Int,
var  totalMinionsKilled	:Int,
var  totalTimeCCDealt	:Int,
var  totalTimeSpentDead	:Int,
var  totalUnitsHealed	:Int,
var  tripleKills	:Int,
var  trueDamageDealt:Int,
var  trueDamageDealtToChampions	:Int,
var  trueDamageTaken:Int,
var  turretKills	:Int,
var  turretTakedowns:Int,
var  turretsLost	:Int,
var  unrealKills	:Int,
var  visionScore	:Int,
var  visionWardsBoughtInGame:Int,
var  wardsKilled	:Int,
var  wardsPlaced	:Int,
var  win:Boolean,

):Serializable {
}