package com.zeroheat.lolandroll.datas

import java.io.Serializable

class matchPartyPeople(

var  assists	:Int,
var  baronKills	:Int,
var  bountyLevel:Int,
var  champExperience:Int,
var  champLevel	:Int,
var  championId	:Int,
var  championName	:String,
var  championTransform	:Int,
var  consumablesPurchased:Int,
var  damageDealtToBuildings:Int,
var  damageDealtToObjectives:Int,
var  damageDealtToTurrets:Int,
var  damageSelfMitigated:Int,
var  deaths	:Int,
var  detectorWardsPlaced:Int,
var  doubleKills:Int,
var  dragonKills:Int,
var  firstBloodAssist:Boolean,
var  firstBloodKill	:Boolean,
var  firstTowerAssist:Boolean,
var  firstTowerKill	:Boolean,
var  gameEndedInEarlySurrender:Boolean,
var  gameEndedInSurrender	:Boolean,
var  goldEarned:Int,
var  goldSpent	:Int,
var  individualPosition:String,
var  inhibitorKills	:Int,
var  inhibitorTakedowns	:Int,
var  inhibitorsLost	:Int,
var  item0	:Int,
var  item1	:Int,
var  item2	:Int,
var  item3	:Int,
var  item4	:Int,
var  item5	:Int,
var  item6	:Int,
var  itemsPurchased	:Int,
var  killingSprees	:Int,
var  kills	:Int,
var  lane	:String,
var  largestCriticalStrike	:Int,
var  largestKillingSpree	:Int,
var  largestMultiKill	:Int,
var  longestTimeSpentLiving	:Int,
var  magicDamageDealt	:Int,
var  magicDamageDealtToChampions:Int,
var  magicDamageTaken:Int,
var  neutralMinionsKilled:Int,
var  nexusKills:Int,
var  nexusTakedowns	:Int,
var  nexusLost	:Int,
var  objectivesStolen:Int,
var  objectivesStolenAssists:Int,
var  participantId:Int,
var  pentaKills	:Int,
var  physicalDamageDealt:Int,
var  physicalDamageDealtToChampions:Int,
var  physicalDamageTaken:Int,
var  profileIcon:Int,
var  puuid	:String,
var  quadraKills:Int,
var  riotIdName	:String,
var  riotIdTagline	:String,
var  role	:String,
var  sightWardsBoughtInGame:Int,
var  spell1Casts	:Int,
var  spell2Casts	:Int,
var  spell3Casts	:Int,
var  spell4Casts	:Int,
var  summoner1Casts	:Int,
var  summoner1Id	:Int,
var  summoner2Casts	:Int,
var  summoner2Id	:Int,
var  summonerId	:String,
var  summonerLevel	:Int,
var  summonerName	:String,
var  teamEarlySurrendered:Boolean,
var  teamId	:Int,
var  teamPosition	:String,
var  timeCCingOthers	:Int,
var  timePlayed	:Int,
var  totalDamageDealt	:Int,
var  totalDamageDealtToChampions	:Int,
var  totalDamageShieldedOnTeammates	:Int,
var  totalDamageTaken	:Int,
var  totalHeal	:Int,
var  totalHealsOnTeammates:Int,
var  totalMinionsKilled	:Int,
var  totalTimeCCDealt	:Int,
var  totalTimeSpentDead	:Int,
var  totalUnitsHealed	:Int,
var  tripleKills	:Int,
var  trueDamageDealt:Int,
var  trueDamageDealtToChampions	:Int,
var  trueDamageTaken:Int,
var  turretKills	:Int,
var  turretTakedowns:Int,
var  turretsLost	:Int,
var  unrealKills	:Int,
var  visionScore	:Int,
var  visionWardsBoughtInGame:Int,
var  wardsKilled	:Int,
var  wardsPlaced	:Int,
var  win:Boolean,

):Serializable {
    fun getLongHashMap() : HashMap<String,Any>{
        val hashMap = hashMapOf<String,Any>(
    "assists"   to this.assists.toString(),
    "baronKills"   to this.baronKills.toString(),
    "bountyLevel"   to this.bountyLevel.toString(),
    "champExperience"   to this.champExperience.toString(),
    "champLevel"   to this.champLevel.toString(),
    "championId"   to this.championId.toString(),
    "championName"   to this.championName,
    "championTransform"   to this.championTransform.toString(),
    "consumablesPurchased"   to this.consumablesPurchased.toString(),
    "damageDealtToBuildings"   to this.damageDealtToBuildings.toString(),
    "damageDealtToObjectives"   to this.damageDealtToObjectives.toString(),
    "damageDealtToTurrets"   to this.damageDealtToTurrets.toString(),
    "damageSelfMitigated"   to this.damageSelfMitigated.toString(),
    "deaths"   to this.deaths.toString(),
    "detectorWardsPlaced"   to this.detectorWardsPlaced.toString(),
    "doubleKills"   to this.doubleKills.toString(),
    "dragonKills"   to this.dragonKills.toString(),
    "firstBloodAssist"   to this.firstBloodAssist.toString(),
    "firstBloodKill"   to this.firstBloodKill.toString(),
    "firstTowerAssist"   to this.firstTowerAssist.toString(),
    "firstTowerKill"   to this.firstTowerKill.toString(),
    "gameEndedInEarlySurrender"   to this.gameEndedInEarlySurrender.toString(),
    "gameEndedInSurrender"   to this.gameEndedInSurrender.toString(),
    "goldEarned"   to this.goldEarned.toString(),
    "goldSpent"   to this.goldSpent.toString(),
    "individualPosition"   to this.individualPosition,
    "inhibitorKills"   to this.inhibitorKills.toString(),
    "inhibitorTakedowns"   to this.inhibitorTakedowns.toString(),
    "inhibitorsLost"   to this.inhibitorsLost.toString(),
    "item0"   to this.item0.toString(),
    "item1"   to this.item1.toString(),
    "item2"   to this.item2.toString(),
    "item3"   to this.item3.toString(),
    "item4"   to this.item4.toString(),
    "item5"   to this.item5.toString(),
    "item6"   to this.item6.toString(),
    "itemsPurchased"   to this.itemsPurchased.toString(),
    "killingSprees"   to this.killingSprees.toString(),
    "kills"   to this.kills.toString(),
    "lane"   to this.lane,
    "largestCriticalStrike"   to this.largestCriticalStrike.toString(),
    "largestKillingSpree"   to this.largestKillingSpree.toString(),
    "largestMultiKill"   to this.largestMultiKill.toString(),
    "longestTimeSpentLiving"   to this.longestTimeSpentLiving.toString(),
    "magicDamageDealt"   to this.magicDamageDealt.toString(),
    "magicDamageDealtToChampions"   to this.magicDamageDealtToChampions.toString(),
    "magicDamageTaken"   to this.magicDamageTaken.toString(),
    "neutralMinionsKilled"   to this.neutralMinionsKilled.toString(),
    "nexusKills"   to this.nexusKills.toString(),
    "nexusTakedowns"   to this.nexusTakedowns.toString(),
    "nexusLost"   to this.nexusLost.toString(),
    "objectivesStolen"   to this.objectivesStolen.toString(),
    "objectivesStolenAssists"   to this.objectivesStolenAssists.toString(),
    "participantId"   to this.participantId.toString(),
    "pentaKills"   to this.pentaKills.toString(),
//    "perks"   to this.perks
    "physicalDamageDealt"   to this.physicalDamageDealt.toString(),
    "physicalDamageDealtToChampions"  to this.physicalDamageDealtToChampions.toString(),
    "physicalDamageTaken"   to this.physicalDamageTaken.toString(),
    "profileIcon"   to this.profileIcon.toString(),
    "puuid"   to this.puuid,
    "quadraKills"   to this.quadraKills.toString(),
    "riotIdName"   to this.riotIdName,
    "riotIdTagline"   to this.riotIdTagline,
    "role"   to this.role,
    "sightWardsBoughtInGame"   to this.sightWardsBoughtInGame.toString(),
    "spell1Casts"   to this.spell1Casts.toString(),
    "spell2Casts"   to this.spell2Casts.toString(),
    "spell3Casts"   to this.spell3Casts.toString(),
    "spell4Casts"   to this.spell4Casts.toString(),
    "summoner1Casts"   to this.summoner1Casts.toString(),
    "summoner1Id"   to this.summoner1Id.toString(),
    "summoner2Casts"   to this.summoner2Casts.toString(),
    "summoner2Id"   to this.summoner2Id.toString(),
    "summonerId"   to this.summonerId,
    "summonerLevel"   to this.summonerLevel.toString(),
    "summonerName"   to this.summonerName,
    "teamEarlySurrendered"   to this.teamEarlySurrendered.toString(),
    "teamId"   to this.teamId.toString(),
    "teamPosition"   to this.teamPosition,
    "timeCCingOthers"   to this.timeCCingOthers.toString(),
    "timePlayed"   to this.timePlayed.toString(),
    "totalDamageDealt"   to this.totalDamageDealt.toString(),
    "totalDamageDealtToChampions"   to this.totalDamageDealtToChampions.toString(),
    "totalDamageShieldedOnTeammates"  to this.totalDamageShieldedOnTeammates.toString(),
    "totalDamageTaken"   to this.totalDamageTaken.toString(),
    "totalHeal"   to this.totalHeal.toString(),
    "totalHealsOnTeammates"   to this.totalHealsOnTeammates.toString(),
    "totalMinionsKilled"   to this.totalMinionsKilled.toString(),
    "totalTimeCCDealt"   to this.totalTimeCCDealt.toString(),
    "totalTimeSpentDead"   to this.totalTimeSpentDead.toString(),
    "totalUnitsHealed"   to this.totalUnitsHealed.toString(),
    "tripleKills"   to this.tripleKills.toString(),
    "trueDamageDealt"   to this.trueDamageDealt.toString(),
    "trueDamageDealtToChampions"   to this.trueDamageDealtToChampions.toString(),
    "trueDamageTaken"   to this.trueDamageTaken.toString(),
    "turretKills"   to this.turretKills.toString(),
    "turretTakedowns"   to this.turretTakedowns.toString(),
    "turretsLost"   to this.turretsLost.toString(),
    "unrealKills"   to this.unrealKills.toString(),
    "visionScore"   to this.visionScore.toString(),
    "visionWardsBoughtInGame"   to this.visionWardsBoughtInGame.toString(),
    "wardsKilled"   to this.wardsKilled.toString(),
    "wardsPlaced"   to this.wardsPlaced.toString(),
    "win"   to this.win.toString(),
        )
        return hashMap
    }
}